# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzban-api.api.user_template_api import UserTemplateApi


class TestUserTemplateApi(unittest.TestCase):
    """UserTemplateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserTemplateApi()

    def tearDown(self) -> None:
        pass

    def test_add_user_template_api_user_template_post(self) -> None:
        """Test case for add_user_template_api_user_template_post

        Add User Template
        """
        pass

    def test_get_user_template_api_user_template_id_get(self) -> None:
        """Test case for get_user_template_api_user_template_id_get

        Get User Template
        """
        pass

    def test_get_user_templates_api_user_template_get(self) -> None:
        """Test case for get_user_templates_api_user_template_get

        Get User Templates
        """
        pass

    def test_modify_user_template_api_user_template_id_put(self) -> None:
        """Test case for modify_user_template_api_user_template_id_put

        Modify User Template
        """
        pass

    def test_remove_user_template_api_user_template_id_delete(self) -> None:
        """Test case for remove_user_template_api_user_template_id_delete

        Remove User Template
        """
        pass


if __name__ == '__main__':
    unittest.main()
