# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzban_api.api.subscription_api import SubscriptionApi


class TestSubscriptionApi(unittest.TestCase):
    """SubscriptionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionApi()

    def tearDown(self) -> None:
        pass

    def test_user_subscription_info_sub_token_info_get(self) -> None:
        """Test case for user_subscription_info_sub_token_info_get

        User Subscription Info
        """
        pass

    def test_user_subscription_sub_token_get(self) -> None:
        """Test case for user_subscription_sub_token_get

        User Subscription
        """
        pass

    def test_user_subscription_with_client_type_sub_token_client_type_get(self) -> None:
        """Test case for user_subscription_with_client_type_sub_token_client_type_get

        User Subscription With Client Type
        """
        pass


if __name__ == '__main__':
    unittest.main()
