# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzban-api.models.proxy_types import ProxyTypes

class TestProxyTypes(unittest.TestCase):
    """ProxyTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProxyTypes(self):
        """Test ProxyTypes"""
        # inst = ProxyTypes()

if __name__ == '__main__':
    unittest.main()
