# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzban-api.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_add_user_api_user_post(self) -> None:
        """Test case for add_user_api_user_post

        Add User
        """
        pass

    def test_delete_expired_api_users_expired_delete(self) -> None:
        """Test case for delete_expired_api_users_expired_delete

        Delete Expired
        """
        pass

    def test_get_user_api_user_username_get(self) -> None:
        """Test case for get_user_api_user_username_get

        Get User
        """
        pass

    def test_get_user_usage_api_user_username_usage_get(self) -> None:
        """Test case for get_user_usage_api_user_username_usage_get

        Get User Usage
        """
        pass

    def test_get_users_api_users_get(self) -> None:
        """Test case for get_users_api_users_get

        Get Users
        """
        pass

    def test_modify_user_api_user_username_put(self) -> None:
        """Test case for modify_user_api_user_username_put

        Modify User
        """
        pass

    def test_remove_user_api_user_username_delete(self) -> None:
        """Test case for remove_user_api_user_username_delete

        Remove User
        """
        pass

    def test_reset_user_data_usage_api_user_username_reset_post(self) -> None:
        """Test case for reset_user_data_usage_api_user_username_reset_post

        Reset User Data Usage
        """
        pass

    def test_reset_users_data_usage_api_users_reset_post(self) -> None:
        """Test case for reset_users_data_usage_api_users_reset_post

        Reset Users Data Usage
        """
        pass

    def test_revoke_user_subscription_api_user_username_revoke_sub_post(self) -> None:
        """Test case for revoke_user_subscription_api_user_username_revoke_sub_post

        Revoke User Subscription
        """
        pass

    def test_set_owner_api_user_username_set_owner_put(self) -> None:
        """Test case for set_owner_api_user_username_set_owner_put

        Set Owner
        """
        pass


if __name__ == '__main__':
    unittest.main()
