# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzban-api.models.user_status import UserStatus

class TestUserStatus(unittest.TestCase):
    """UserStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserStatus(self):
        """Test UserStatus"""
        # inst = UserStatus()

if __name__ == '__main__':
    unittest.main()
