# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzban-api.models.core_stats import CoreStats

class TestCoreStats(unittest.TestCase):
    """CoreStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoreStats:
        """Test CoreStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoreStats`
        """
        model = CoreStats()
        if include_optional:
            return CoreStats(
                version = '',
                started = True,
                logs_websocket = ''
            )
        else:
            return CoreStats(
                version = '',
                started = True,
                logs_websocket = '',
        )
        """

    def testCoreStats(self):
        """Test CoreStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
