# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzban_api.api.core_api import CoreApi


class TestCoreApi(unittest.TestCase):
    """CoreApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CoreApi()

    def tearDown(self) -> None:
        pass

    def test_get_core_config_api_core_config_get(self) -> None:
        """Test case for get_core_config_api_core_config_get

        Get Core Config
        """
        pass

    def test_get_core_stats_api_core_get(self) -> None:
        """Test case for get_core_stats_api_core_get

        Get Core Stats
        """
        pass

    def test_modify_core_config_api_core_config_put(self) -> None:
        """Test case for modify_core_config_api_core_config_put

        Modify Core Config
        """
        pass

    def test_restart_core_api_core_restart_post(self) -> None:
        """Test case for restart_core_api_core_restart_post

        Restart Core
        """
        pass


if __name__ == '__main__':
    unittest.main()
