# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from marzban_api.api.node_api import NodeApi


class TestNodeApi(unittest.TestCase):
    """NodeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NodeApi()

    def tearDown(self) -> None:
        pass

    def test_add_node_api_node_post(self) -> None:
        """Test case for add_node_api_node_post

        Add Node
        """
        pass

    def test_get_node_api_node_node_id_get(self) -> None:
        """Test case for get_node_api_node_node_id_get

        Get Node
        """
        pass

    def test_get_node_api_node_settings_get(self) -> None:
        """Test case for get_node_api_node_settings_get

        Get Node
        """
        pass

    def test_get_nodes_api_nodes_get(self) -> None:
        """Test case for get_nodes_api_nodes_get

        Get Nodes
        """
        pass

    def test_get_usage_api_nodes_usage_get(self) -> None:
        """Test case for get_usage_api_nodes_usage_get

        Get Usage
        """
        pass

    def test_modify_node_api_node_node_id_put(self) -> None:
        """Test case for modify_node_api_node_node_id_put

        Modify Node
        """
        pass

    def test_reconnect_node_api_node_node_id_reconnect_post(self) -> None:
        """Test case for reconnect_node_api_node_node_id_reconnect_post

        Reconnect Node
        """
        pass

    def test_remove_node_api_node_node_id_delete(self) -> None:
        """Test case for remove_node_api_node_node_id_delete

        Remove Node
        """
        pass


if __name__ == '__main__':
    unittest.main()
