# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProxyHostALPN(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    EMPTY = ''
    H2 = 'h2'
    HTTP_SLASH_1_DOT_1 = 'http/1.1'
    H2_COMMA_HTTP_SLASH_1_DOT_1 = 'h2,http/1.1'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProxyHostALPN from a JSON string"""
        return cls(json.loads(json_str))


