# coding: utf-8

"""
    MarzbanAPI

    Unified GUI Censorship Resistant Solution Powered by Xray

    The version of the OpenAPI document: 0.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class UserTemplateModify(BaseModel):
    """
    UserTemplateModify
    """ # noqa: E501
    name: Optional[StrictStr] = None
    data_limit: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="data_limit can be 0 or greater")
    expire_duration: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="expire_duration can be 0 or greater in seconds")
    username_prefix: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=20)]] = None
    username_suffix: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=20)]] = None
    inbounds: Optional[Dict[str, List[StrictStr]]] = None
    __properties: ClassVar[List[str]] = ["name", "data_limit", "expire_duration", "username_prefix", "username_suffix", "inbounds"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserTemplateModify from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserTemplateModify from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "data_limit": obj.get("data_limit"),
            "expire_duration": obj.get("expire_duration"),
            "username_prefix": obj.get("username_prefix"),
            "username_suffix": obj.get("username_suffix"),
            "inbounds": obj.get("inbounds")
        })
        return _obj


